version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10  # Official CircleCI Python image
    steps:
      - checkout  # Pulls your repo code

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest  # or python -m unittest

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
