version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: List test files
          command: |
            echo "Listing files in tests/ directory:"
            ls -al tests/
      - run:
          name: Run tests
          command: pytest tests/

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
